apiVersion: v1
kind: PersistentVolume  #this is PV
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi     #create volume 20gb in aws
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b0dadabfae7c5315
---
apiVersion: v1
kind: PersistentVolumeClaim  #this is pvc(claim)
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  #there is 20gb you cant ask/acces more than that