apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi     #create volume 20gb in aws
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b0dadabfae7c5315