apiVersion: v1
kind: PersistentVolume  #this is PV
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi     #create volume 20gb in aws
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-01c7c69db0318e2a9
---
apiVersion: v1
kind: PersistentVolumeClaim  #this is pvc(claim)
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  #there is 20gb you cant ask/acces more than that
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels: 
    purpose: ebs-static
spec:
  nodeSelector:
   topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:            #volumemount is equlent to docker run -v hostpath:containerpath
    - name: my-ebs-volume     # name inside the container
      mountPath: /usr/share/nginx/html #in this path ebs volume should access 
  volumes:
  - name: my-ebs-volume       # this must match the name above in volume mount
    persistentVolumeClaim:
      claimName: ebs-static-claim
---
kind: Service
apiVersion: v1 

metadata: 
  name: nginx-lb
  
spec: 
  type: LoadBalancer
  selector:
    purpose: ebs-static   # it should match with pod labels
  ports: 
  - name: nginx-service-port 
    protocol: TCP
    port: 80  # Service port (exposed to the outside world)
    targetPort: 80 #this is service port 
    nodePort: 30007 #open this port in awsnsg(sg)