apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs-stgclass
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer #storage will be created when pods is getting created 