kind: Pod 
apiVersion: v1 

metadata: 
 name: environment


spec: 
 containers: 
  - name: nginx
    image: nginx 
    env: 
     - name: DEMO_GREETING
       value: "Hello from the environment"
     - name: DEMO_FAREWELL
       value: "Such a sweet sorrow" 
     - name: duration
       value: "120hr" 
  