kind: Pod
apiVersion: v1 
metadata: 
 name: pod-configmap-ref

spec: 
 containers: 
  - name: nginx
    image: nginx 
    env: 
     - name: course 
       valueFrom:
        configMapKeyRef:
          name: nginx-config      # Name of the config-map your refering to. 
          key: course  #env.name and config-map key name can be different or same there is nothing.
     - name: duration 
       valueFrom:
         configMapKeyRef: 
          name: nginx-config
          key: duration