apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: Opaque # Arbitrary user-defined data (like passwords, API keys, tokens, etc.) you can store any kind of secret data (like passwords, tokens, keys). You define the key and value — Kubernetes doesn't care what they are.
data:
 username: QmFzYXZhcmFqCg==
 password: QWRtaW5AMTIzCg==

