kind: Service
apiVersion: v1 

metadata: 
  name: nginx 

spec: 
  selector:
    project: expense #This means the Service will automatically route traffic to any Pod that has matching labels.
    module: backend
    environment: dev
  ports: 
  - name: nginx-service-port 
    protocol: TCP
    port: 80 #this is service port 
    targetPort: 80  #this is container port here you can use names of the ports aswell example: http-web-svc

      
 