kind: Service
apiVersion: v1 

metadata: 
  name: nginx-node-port

spec: 
  type: NodePort
  selector:
    project: expense 
    module: backend
    environment: dev
  ports: 
  - name: nginx-service-port 
    protocol: TCP
    port: 80      # Service port (exposed to the outside world)
    targetPort: 80 # Container port (inside the pod) 