kind: Service
apiVersion: v1 

metadata: 
  name: nginx-load-balancer

spec: 
  type: LoadBalancer
  selector:
    project: expense 
    module: backend
    environment: dev
  ports: 
  - name: nginx-service-port 
    protocol: TCP
    port: 80 #this is service port 
    targetPort: 80